---
- name: API call
  uri:
    url: https://{{ inventory_hostname }}/api/
    method: POST
    headers:
      Cookie: "{{ token }}"
      APIC-challenge: "{{ urlToken }}"
    validate_certs: no
    body_format: json
    body: >
  register: response
