---
- name: ACI - Creating VRF
  uri:
    url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant_name }}/ctx-{{ item.vrf_name }}.json
    method: POST
    headers:
      Cookie: "{{ token }}"
      APIC-challenge: "{{ urlToken }}"
    validate_certs: no
    body_format: json
    body: >
      {
        "fvCtx": {
                "attributes": {
                        "name": "{{ item.vrf_name }}"
                },
        }
      }
  register: vrf
  with_items:
    - "{{ aci_vrf }}"
