---
- name: Cisco ACI - Creating new tenant
  uri:
    url: https://{{ inventory_hostname }}/api/node/mo/uni/tn-{{ item.tenant_name }}.json
    method: POST
    headers:
      Cookie: "{{ token }}"
      APIC-challenge: "{{ urlToken }}"
    validate_certs: no
    body_format: json
    body: >
      {
        "fvTenant": {
                "attributes": {
                        "name": "{{ item.tenant_name }}",
                },
        }
      }
  register: tenant
  with_items:
    - "{{ aci_tenant }}"
